### ISSUE TITLE
Rename repo to keylime-vagrant-ansible-tpm-emulator

### ISSUE THREAD

**Issue by axelsimon** [keylime/keylime-vagrant-ansible-tpm-emulator#46]
As discussed with @mpeters, this repo is much more about providing an way to try out Keylime using Vagrant than about the Ansible part, which is just means to that end.

In light of that, i suggest renaming the repo from `ansible-keylime-tpm-emulator` to `vagrant-keylime-tpm-emulator`.

If there is no blocking opposition in the next 8 days, i will proceed with this change on Friday 2020-12-18 :slightly_smiling_face:

Suggestions welcome as to a better name if you have one, of course.

**Comment by mpeters** [comment]
I agree with this change :)

**Comment by axelsimon** [comment]
Reminder (to myself) that this will require an update to keylime.dev ("Ansible role with a TPM emulator..").

**Comment by axelsimon** [comment]
Done today, repo's name is now keylime-vagrant-ansible-tpm-emulator
