### ISSUE TITLE
Source /root/keylime/ima_stub_service/tpm_emulator.service not found

### ISSUE THREAD

**Issue by koh-osug** [keylime/keylime-vagrant-ansible-tpm-emulator#74]
When installing keylime in virtualbox with:

~~~shell
vagrant --instances=2 --cpus=4 --memory=4096  up --provider virtualbox --provision
~~~

I get the following error:

> TASK [ansible-keylime-tpm20 : Install tpm_server] ******************************
> changed: [keylime-fedora1] => {"changed": true, "checksum": "0bceb9ab5ed6b55820b030dcee38df53cf11774f", "dest": "/usr/local/bin/tpm_server", "gid": 0, "group": "root", "md5sum": "131af37535f1f57a3a5f30ae78b8be59", "mode": "0744", "owner": "root", "secontext": "system_u:object_r:bin_t:s0", "size": 1074272, "src": "/root/ibmtpm/src/tpm_server", "state": "file", "uid": 0}
> 
> TASK [ansible-keylime-tpm20 : Set TPM2TOOLS_TCTI environment variable globally] ***
> changed: [keylime-fedora1] => {"backup": "", "changed": true, "msg": "line added"}
> 
> TASK [ansible-keylime-tpm20 : Install TPM Emulator service] ********************
> fatal: [keylime-fedora1]: FAILED! => {"changed": false, "msg": "Source /root/keylime/ima_stub_service/tpm_emulator.service not found"}
> 
> PLAY RECAP *********************************************************************
> keylime-fedora1            : ok=23   changed=20   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
> 
> Ansible failed to complete successfully. Any error output should be
> visible above. Please fix these errors and try again.

**Comment by THS-on** [comment]
The Vagrant setup is currently not maintained and likely replaced by another mechanism, see https://github.com/keylime/keylime/issues/1342 for more

**Comment by THS-on** [comment]
Closing in favor of #75
